import { useState, createContext } from "react";
import BooleanEgyptian from './img/Rectangle 308.png';
import RoadToEgypt from './img/Rectangle 62.png';
import Blanc from './img/Rectangle 62 (1).png';
import Ellipsia from './img/Rectangle 62 (2).png';
import Lawmakers from './img/Rectangle 62 (3).png';
import Sassy from "./img/Rectangle 254.png";
import bougie from "./img/Rectangle 256.png";
import lost from "./img/Rectangle 258.png";
import circa from "./img/Rectangle 260.png";
import firsy from "./img/Rectangle 39.png";
import secindy from "./img/Rectangle 284.png";
import thirdy from "./img/Rectangle 287.png";

export const ProductContext = createContext();
export const CartContext = createContext();

export const ProductProvider = ( props ) => {
    const [products, setProducts] = useState([
        {
            id:0,
            type: "Editorial",
            ref: "Philomena",
            name:"Boolean Egyptian",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.5,
            img: BooleanEgyptian,
            quantity:1,
        },
        {
            id:1,
            type: "Fashion",
            ref: "Warped",
            name:"Blanc",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.50,
            img: Blanc,
            quantity:1,
        },
        {
            id:2,
            type: "Fashion",
            ref: "Warped",
            name:"Blanc",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.50,
            img: Blanc,
            quantity:1,
        },
        {
            id:3,
            type: "Optics",
            ref: "Ellipsia",
            name:"Road To Egypt",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.50,
            img: RoadToEgypt,
            quantity:1,
        },
        {
            id:4,
            type: "Ellipsia",
            ref: "Philomena",
            name:"Boolean Egyptian",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.50,
            img: Ellipsia,
            quantity:1,
        },
        {
            id:5,
            type: "Nature",
            ref: "Warped",
            name:"Lawmaker",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.50,
            img: Lawmakers,
            quantity:1,
        },
        {
            id:6,
            type: "Editorial",
            ref: "Ellipsia",
            name:"Sassy",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.50,
            img: Sassy,
            quantity:1,
        },
        {
            id:7,
            type: "Fashion",
            ref: "Philomena",
            name:"Bougie",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.50,
            img: bougie,
            quantity:1,
        },
        {
            id:8,
            type: "Optics",
            ref: "Warped",
            name:"Lost",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.50,
            img: lost,
            quantity:1,
        },
        {
            id:9,
            type: "Arts & Museum",
            ref: "Ellipsia",
            name:"Circa",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.50,
            img: circa,
            quantity:1,
        },
        {
            id:10,
            type: "Nature",
            ref: "Warped",
            name:"Boolean Egyptian",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.50,
            img: BooleanEgyptian,
            quantity:1,
        },
        {
            id:11,
            type: "Editorial",
            ref: "Ellipsia",
            name:"Boolean Egyptian",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.50,
            img: BooleanEgyptian,
            quantity:1,
        },
        {
            id:12,
            type: "Fashion",
            ref: "Philomena",
            name:"Boolean Egyptian",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.50,
            img: BooleanEgyptian,
            quantity:1,
        },
        {
            id:13,
            type: "Optics",
            ref: "Warped",
            name:"Boolean Egyptian",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.50,
            img: BooleanEgyptian,
            quantity:1,
        },
        {
            id:14,
            type: "Art & Museum",
            ref: "Ellipsia",
            name:"Boolean Egyptian",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.50,
            img: BooleanEgyptian,
            quantity:1,
        },
        {
            id:15,
            type: "Nature",
            ref: "Philomena",
            name:"Boolean Egyptian",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.50,
            img: BooleanEgyptian,
            quantity:1,
        },
        {
            id:16,
            type: "Editorial",
            ref: "Warped",
            name:"Boolean Egyptian",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.50,
            img: BooleanEgyptian,
            quantity:1,
        },
        {
            id:17,
            type: "Fashion",
            ref: "Ellipsia",
            name:"Boolean Egyptian",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.50,
            img: BooleanEgyptian,
            quantity:1,
        },
        {
            id:18,
            type: "Optics",
            ref: "Philomena",
            name:"Boolean Egyptian",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.50,
            img: BooleanEgyptian,
            quantity:1,
        },
        {
            id:19,
            type: "Art & Museum",
            ref: "Warped",
            name:"Boolean Egyptian",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.50,
            img: BooleanEgyptian,
            quantity:1,
        },
        {
            id:20,
            type: "Nature",
            ref: "Ellipsia",
            name:"Boolean Egyptian",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.50,
            img: BooleanEgyptian,
            quantity:1,
        },
        {
            id:21,
            type: "Editorial",
            ref: "Philomena",
            name:"Boolean Egyptian",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.5,
            img: BooleanEgyptian,
            quantity:1,
        },
        {
            id:22,
            type: "Fashion",
            ref: "Warped",
            name:"Blanc",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.50,
            img: Blanc,
            quantity:1,
        },
        {
            id:23,
            type: "Optics",
            ref: "Ellipsia",
            name:"Road To Egypt",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.50,
            img: RoadToEgypt,
            quantity:1,
        },
        {
            id:24,
            type: "Ellipsia",
            ref: "Philomena",
            name:"Boolean Egyptian",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.50,
            img: Ellipsia,
            quantity:1,
        },
        {
            id:25,
            type: "Nature",
            ref: "Warped",
            name:"Lawmaker",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.50,
            img: Lawmakers,
            quantity:1,
        },
        {
            id:26,
            type: "Editorial",
            ref: "Ellipsia",
            name:"Sassy",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.50,
            img: Sassy,
            quantity:1,
        },
        {
            id:27,
            type: "Fashion",
            ref: "Philomena",
            name:"Bougie",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.50,
            img: bougie,
            quantity:1,
        },
        {
            id:28,
            type: "Optics",
            ref: "Warped",
            name:"Lost",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.50,
            img: lost,
            quantity:1,
        },
        {
            id:29,
            type: "Arts & Museum",
            ref: "Ellipsia",
            name:"Circa",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.50,
            img: circa,
            quantity:1,
        },
        {
            id:30,
            type: "Nature",
            ref: "Warped",
            name:"Boolean Egyptian",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.50,
            img: BooleanEgyptian,
            quantity:1,
        },
        {
            id:31,
            type: "Nature",
            ref: "Warped",
            name:"Boolean Egyptian",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.50,
            img: BooleanEgyptian,
            quantity:1,
        },
        {
            id:32,
            type: "Nature",
            ref: "Warped",
            name:"Boolean Egyptian",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.50,
            img: BooleanEgyptian,
            quantity:1,
        },
        {
            id:33,
            type: "Nature",
            ref: "Warped",
            name:"Boolean Egyptian",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.50,
            img: firsy,
            quantity:1,
        },
        {
            id:34,
            type: "Nature",
            ref: "Warped",
            name:"Boolean Egyptian",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.50,
            img: secindy,
            quantity:1,
        },
        {
            id:35,
            type: "Nature",
            ref: "Warped",
            name:"Boolean Egyptian",
            size: "200 ft",
            creator: "Clearamane",
            price: 36.50,
            img: thirdy,
            quantity:1,
        },
        
        
    ])


    return(
        <ProductContext.Provider value={[products, setProducts]}>
            {props.children}
        </ProductContext.Provider>
    )
} 